### ISSUE TITLE
Error deploying plugin (following the referenced guide)

### ISSUE THREAD

**Issue by agibson-vrnt** [awslabs/aws-codepipeline-plugin-for-jenkins#6]
Trying to upload the plug-in as mentioned in the Getting Started guide, I receive the following error (tried multiple times). Is the current dist a valid zip file?

```
java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1328)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at hudson.ClassicPluginStrategy.getShortName(ClassicPluginStrategy.java:107)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:439)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1324)
	... 5 more
```

**Comment by agibson-vrnt** [comment]
It appears this was caused by incorrectly downloading the file from github via the web page. You might want to add some instructions about how to download the hpi as "raw" to prevent people making the same mistake.
